/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomerForm.java
 *
 * Created on Jun 29, 2011, 9:44:57 PM
 */
package yhc.inventory;


import java.awt.Image;
import java.sql.Statement;
import javax.swing.*;

/**
 *
 * @author Saqib
 */
public class CustomerForm extends JFrame {
    
    ImageIcon tick = new ImageIcon(getClass().getResource("tick.jpg"));
    ImageIcon cross = new ImageIcon(getClass().getResource("cross.jpg"));

    /** Creates new form CustomerForm */
    public CustomerForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCustomerNumber = new javax.swing.JLabel();
        txtCustomerNumber = new javax.swing.JTextField();
        lblCustomerFirstName = new javax.swing.JLabel();
        lblCustomerPhone = new javax.swing.JLabel();
        txtCustomerPhone = new javax.swing.JTextField();
        lblCustomerStreet = new javax.swing.JLabel();
        txtCustomerStreet = new javax.swing.JTextField();
        lblCustomerEmail = new javax.swing.JLabel();
        txtCustomerEmail = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtCustomerName = new javax.swing.JTextField();
        lblCutomerCity = new javax.swing.JLabel();
        txtCustomerCity = new javax.swing.JTextField();
        imgCustomerPhone = new javax.swing.JLabel();
        imgCity = new javax.swing.JLabel();
        imgEmail = new javax.swing.JLabel();
        imgStreet = new javax.swing.JLabel();
        imgName = new javax.swing.JLabel();
        backgroundPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Customer");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblTitle.setText("Customer Information");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 11, -1, -1));

        lblCustomerNumber.setBackground(new java.awt.Color(255, 255, 255));
        lblCustomerNumber.setText("Customer ID: ");
        getContentPane().add(lblCustomerNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, -1, -1));

        txtCustomerNumber.setBackground(new java.awt.Color(251, 247, 247));
        txtCustomerNumber.setEditable(false);
        txtCustomerNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtCustomerNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 46, 310, -1));

        lblCustomerFirstName.setText("Customer Name: ");
        getContentPane().add(lblCustomerFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, -1, -1));

        lblCustomerPhone.setText("Customer Phone: ");
        getContentPane().add(lblCustomerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, -1, -1));

        txtCustomerPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerPhoneFocusLost(evt);
            }
        });
        getContentPane().add(txtCustomerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 103, 310, 25));

        lblCustomerStreet.setText("Customer Street:");
        lblCustomerStreet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCustomerStreetMouseEntered(evt);
            }
        });
        getContentPane().add(lblCustomerStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txtCustomerStreet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerStreetFocusLost(evt);
            }
        });
        getContentPane().add(txtCustomerStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 134, 310, 27));

        lblCustomerEmail.setText("Customer Email: ");
        getContentPane().add(lblCustomerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 203, -1, -1));

        txtCustomerEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerEmailFocusLost(evt);
            }
        });
        getContentPane().add(txtCustomerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 198, 310, 25));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 234, 70, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 234, 74, -1));

        txtCustomerName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerNameFocusLost(evt);
            }
        });
        getContentPane().add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 72, 310, 25));

        lblCutomerCity.setText("Customer City:");
        getContentPane().add(lblCutomerCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 172, -1, -1));

        txtCustomerCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerCityFocusLost(evt);
            }
        });
        getContentPane().add(txtCustomerCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 167, 310, 25));
        getContentPane().add(imgCustomerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 103, -1, 25));
        getContentPane().add(imgCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 162, 30, 30));
        getContentPane().add(imgEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 198, -1, 25));
        getContentPane().add(imgStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 134, -1, 27));
        getContentPane().add(imgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 72, -1, 25));

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 192, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(460, 36));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNumberActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String name      = txtCustomerName.getText();
        String street    = txtCustomerStreet.getText();
        String city      = txtCustomerCity.getText();
        String phone     = txtCustomerPhone.getText();
        String email     = txtCustomerEmail.getText();
        
        String insertQuery = String.format("Insert INTO Customers(Name, Street, City, Phone, Email) VALUES ('%s', '%s', '%s', '%s', '%s');", name, street, city, phone, email);

        Statement stmt = DatabaseConnection.getStatement();
        try {
            int rowAffected = stmt.executeUpdate(insertQuery);
            JOptionPane.showMessageDialog(null, rowAffected + " record added to the database");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to insert record" + e.toString());
        }
        
        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCustomerPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerPhoneFocusLost
        String phonePattern = "[0-9-]+";
        if(txtCustomerPhone.getText().matches(phonePattern)) 
            imgCustomerPhone.setIcon(tick);
        else
            imgCustomerPhone.setIcon(cross);

    }//GEN-LAST:event_txtCustomerPhoneFocusLost

    private void txtCustomerStreetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerStreetFocusLost
        String streetPattern = "[a-zA-Z0-9#./\\\\ ]+";
        if(txtCustomerStreet.getText().matches(streetPattern))
            imgStreet.setIcon(tick);
        else
            imgStreet.setIcon(cross);
    }//GEN-LAST:event_txtCustomerStreetFocusLost

    private void txtCustomerCityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerCityFocusLost
        String cityPattern = "[a-zA-Z ]+";
        if(txtCustomerCity.getText().matches(cityPattern))
            imgCity.setIcon(tick);
        else
            imgCity.setIcon(cross);
    }//GEN-LAST:event_txtCustomerCityFocusLost

    private void txtCustomerEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerEmailFocusLost
        String emailPattern = "[a-zA-Z0-9._]+@[a-zA-Z0-9_]+\\.[a-zA-Z]+";
        if(txtCustomerEmail.getText().matches(emailPattern))
            imgEmail.setIcon(tick);
        else
            imgEmail.setIcon(cross);
    }//GEN-LAST:event_txtCustomerEmailFocusLost

    private void txtCustomerNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerNameFocusLost
        String namePattern = "[a-zA-Z. ]+";
        if(txtCustomerName.getText().matches(namePattern))
            imgName.setIcon(tick);
        else
            imgName.setIcon(cross);
    }//GEN-LAST:event_txtCustomerNameFocusLost

    private void lblCustomerStreetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerStreetMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCustomerStreetMouseEntered

    @Override
    public void setIconImage(Image image) {
        super.setIconImage(image);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CustomerForm().setVisible(true);
            }
        });
    }
    
    public void setCustomerNumber(int num) {
        txtCustomerNumber.setText(Integer.toString(num));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel imgCity;
    private javax.swing.JLabel imgCustomerPhone;
    private javax.swing.JLabel imgEmail;
    private javax.swing.JLabel imgName;
    private javax.swing.JLabel imgStreet;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCustomerEmail;
    private javax.swing.JLabel lblCustomerFirstName;
    private javax.swing.JLabel lblCustomerNumber;
    private javax.swing.JLabel lblCustomerPhone;
    private javax.swing.JLabel lblCustomerStreet;
    private javax.swing.JLabel lblCutomerCity;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCustomerCity;
    private javax.swing.JTextField txtCustomerEmail;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerNumber;
    private javax.swing.JTextField txtCustomerPhone;
    private javax.swing.JTextField txtCustomerStreet;
    // End of variables declaration//GEN-END:variables
}
