/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomerInformationForm.java
 *
 * Created on Jun 29, 2011, 9:44:57 PM
 */
package yhc.inventory;


import java.awt.Image;
import java.sql.Statement;
import javax.swing.*;

/**
 *
 * @author Saqib
 */
public class VendorForm extends JFrame {
    
    ImageIcon tick = new ImageIcon(getClass().getResource("tick.jpg"));
    ImageIcon cross = new ImageIcon(getClass().getResource("cross.jpg"));

    /** Creates new form CustomerInformationForm */
    public VendorForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSupplierNumber = new javax.swing.JLabel();
        txtSupplierNumber = new javax.swing.JTextField();
        lblSupplieName = new javax.swing.JLabel();
        lblSupplierPhone = new javax.swing.JLabel();
        txtSupplierPhone = new javax.swing.JTextField();
        lblSupplierStreet = new javax.swing.JLabel();
        txtSupplierStreet = new javax.swing.JTextField();
        lblSupplierEmail = new javax.swing.JLabel();
        txtSupplierEmail = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtSupplierName = new javax.swing.JTextField();
        lblSupplierCity = new javax.swing.JLabel();
        txtSupplierCity = new javax.swing.JTextField();
        imgCustomerPhone = new javax.swing.JLabel();
        imgCity = new javax.swing.JLabel();
        imgEmail = new javax.swing.JLabel();
        imgStreet = new javax.swing.JLabel();
        imgName = new javax.swing.JLabel();
        backgroundPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Vendor");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setText("Vendor Information");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 11, -1, -1));

        lblSupplierNumber.setText("Vendor ID: ");
        getContentPane().add(lblSupplierNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, -1, -1));

        txtSupplierNumber.setBackground(new java.awt.Color(251, 247, 247));
        txtSupplierNumber.setEditable(false);
        txtSupplierNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierNumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtSupplierNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 46, 310, -1));

        lblSupplieName.setText("Vendor Name: ");
        getContentPane().add(lblSupplieName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, -1, -1));

        lblSupplierPhone.setText("Vendor Phone: ");
        getContentPane().add(lblSupplierPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, -1, -1));

        txtSupplierPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSupplierPhoneFocusLost(evt);
            }
        });
        getContentPane().add(txtSupplierPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 109, 310, 25));

        lblSupplierStreet.setText("Vendor Street:");
        getContentPane().add(lblSupplierStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 146, -1, -1));

        txtSupplierStreet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSupplierStreetFocusLost(evt);
            }
        });
        getContentPane().add(txtSupplierStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 140, 310, 27));

        lblSupplierEmail.setText("Vendor Email: ");
        getContentPane().add(lblSupplierEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 209, -1, -1));

        txtSupplierEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSupplierEmailFocusLost(evt);
            }
        });
        getContentPane().add(txtSupplierEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 204, 310, 25));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 240, 70, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 240, 74, -1));

        txtSupplierName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSupplierNameFocusLost(evt);
            }
        });
        getContentPane().add(txtSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 75, 310, 28));

        lblSupplierCity.setText("Vendor City:");
        getContentPane().add(lblSupplierCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 178, -1, -1));

        txtSupplierCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSupplierCityFocusLost(evt);
            }
        });
        getContentPane().add(txtSupplierCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 173, 310, 25));
        getContentPane().add(imgCustomerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 109, -1, 25));
        getContentPane().add(imgCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 168, 30, 30));
        getContentPane().add(imgEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 204, -1, 25));
        getContentPane().add(imgStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 140, -1, 27));

        imgName.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(imgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 75, 33, 28));

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 192, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSupplierNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierNumberActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String name      = txtSupplierName.getText();
        String street    = txtSupplierStreet.getText();
        String city      = txtSupplierCity.getText();
        String phone     = txtSupplierPhone.getText();
        String email     = txtSupplierEmail.getText();
        
        String insertQuery = String.format("Insert INTO Vendors(Name, Street, City, Phone, Email) VALUES ('%s', '%s', '%s', '%s', '%s');", name, street, city, phone, email);

        Statement stmt = DatabaseConnection.getStatement();
        try {
            int rowAffected = stmt.executeUpdate(insertQuery);
            JOptionPane.showMessageDialog(null, rowAffected + " record added to the database");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to insert record" + e.toString());
        }
        
        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSupplierPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSupplierPhoneFocusLost
        String phonePattern = "[0-9-]+";
        if(txtSupplierPhone.getText().matches(phonePattern)) 
            imgCustomerPhone.setIcon(tick);
        else
            imgCustomerPhone.setIcon(cross);

    }//GEN-LAST:event_txtSupplierPhoneFocusLost

    private void txtSupplierStreetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSupplierStreetFocusLost
        String streetPattern = "[a-zA-Z0-9#./\\\\ ]+";
        if(txtSupplierStreet.getText().matches(streetPattern))
            imgStreet.setIcon(tick);
        else
            imgStreet.setIcon(cross);
    }//GEN-LAST:event_txtSupplierStreetFocusLost

    private void txtSupplierCityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSupplierCityFocusLost
        String cityPattern = "[a-zA-Z ]+";
        if(txtSupplierCity.getText().matches(cityPattern))
            imgCity.setIcon(tick);
        else
            imgCity.setIcon(cross);
    }//GEN-LAST:event_txtSupplierCityFocusLost

    private void txtSupplierEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSupplierEmailFocusLost
        String emailPattern = "[a-zA-Z0-9._]+@[a-zA-Z0-9_]+\\.[a-zA-Z]+";
        if(txtSupplierEmail.getText().matches(emailPattern))
            imgEmail.setIcon(tick);
        else
            imgEmail.setIcon(cross);
    }//GEN-LAST:event_txtSupplierEmailFocusLost

    private void txtSupplierNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSupplierNameFocusLost
        String namePattern = "[a-zA-Z. ]+";
        if(txtSupplierName.getText().matches(namePattern))
            imgName.setIcon(tick);
        else
            imgName.setIcon(cross);
    }//GEN-LAST:event_txtSupplierNameFocusLost

    @Override
    public void setIconImage(Image image) {
        super.setIconImage(image);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VendorForm().setVisible(true);
            }
        });
    }
    
    public void setSupplierNumber(int num) {
        txtSupplierNumber.setText(Integer.toString(num));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel imgCity;
    private javax.swing.JLabel imgCustomerPhone;
    private javax.swing.JLabel imgEmail;
    private javax.swing.JLabel imgName;
    private javax.swing.JLabel imgStreet;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSupplieName;
    private javax.swing.JLabel lblSupplierCity;
    private javax.swing.JLabel lblSupplierEmail;
    private javax.swing.JLabel lblSupplierNumber;
    private javax.swing.JLabel lblSupplierPhone;
    private javax.swing.JLabel lblSupplierStreet;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtSupplierCity;
    private javax.swing.JTextField txtSupplierEmail;
    private javax.swing.JTextField txtSupplierName;
    private javax.swing.JTextField txtSupplierNumber;
    private javax.swing.JTextField txtSupplierPhone;
    private javax.swing.JTextField txtSupplierStreet;
    // End of variables declaration//GEN-END:variables
}